### PR TITLE
Fix hostgroup.get in Zabbix 6.2

### LINKED ISSUE #1470: The plugin is not working with Zabbix 6.2.0
**Describe the bug**
It looks like grafana is not able to query hosts from the zabbix API (version 6.2)

**Expected behavior**
Query the hosts from zabbix

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 9.0.1   | 6.2.0  | 4.2.8             |

I think the API is changed:

[ZBXNEXT-2592](https://support.zabbix.com/browse/ZBXNEXT-2592) host.get: deprecated option selectGroups, new option selectHostGroups.

[ZBXNEXT-2592](https://support.zabbix.com/browse/ZBXNEXT-2592) hostgroup.get: deprecated options monitored_hosts, real_hosts, new options with_hosts, with_monitored_hosts.

### PR DESCRIPTION
**Pull request by alexanderzobnin**
This PR fixes #1470 by adding `groupid` param explicitly to host groups queries.

### CODE REVIEW

**Comment by leleobhz** [comment]
@alexanderzobnin The deprecation of [`real_hosts`](https://www.zabbix.com/documentation/current/en/manual/api/reference/hostgroup/get) function on [methods.go](https://github.com/alexanderzobnin/grafana-zabbix/pull/1475/files#diff-5bccbe9786d41efb0737084d429a304667518641fbc1eae3a881787ee998d91aR398) and [zabbixAPIConnector.ts](https://github.com/alexanderzobnin/grafana-zabbix/pull/1475/files#diff-574046a31ba66b6bed483a1b597a1615b205e8b962b186e07ba6fc87f08dc22cR139) does not affect this MR?

**Comment by Sam-H101** [comment]
@leleobhz I did test this out, it does work for this release of zabbix anyways. In my opinion, I would still switch from the deprecated functions to save future work.

**Comment by alexanderzobnin** [comment]
I would prefer to update deprecated params in separate PR since it's not critical right now.

**Comment by iny** [comment]
This problem continues in the 4.3.1 version installed via Grafana, has this problem been fixed?

**Comment by leleobhz** [comment]
> This problem continues in the 4.3.1 version installed via Grafana, has this problem been fixed?

This PR may not be related to same issue in https://github.com/alexanderzobnin/grafana-zabbix/issues/1633.

**Pull request merged**
