### PR TITLE
Implemet client-side metric aggregation

### PR DESCRIPTION
**Pull request by olfway**
Initial implementation, I've tested it myself, seems to work :)
What do you think? any comments?

### CODE REVIEW

**Comment by alexanderzobnin** [comment]
Cool work, @olfway ! I need some time for tests, if all is OK, I will merge this PR. Thanks!

**Comment by olfway** [comment]
@alexanderzobnin do you had a chance to look at it?

**Comment by alexanderzobnin** [comment]
@olfway Sorry, still have no time to test it.

**Comment by xmj** [comment]
Hi, how do we help moving this item forward?

**Comment by alexanderzobnin** [comment]
@xmj I working on version for Grafana 3.0 and want to implement aggregations in it. Before I need to do some preparatory work. There are meny changes in next version and I can't give you clear explanation how to implement it right now. Wait some time (about few weeks) please.

**Comment by alexanderzobnin** [comment]
Closed. It was implemented.

**Pull request closed without merging**
