### PR TITLE
Item select and regex filter with macro replacement

### PR DESCRIPTION
**Pull request by christianchristensen**
See also: https://support.zabbix.com/browse/ZBXNEXT-2841

### CODE REVIEW

**Comment by christianchristensen** [comment]
Before:
screenshot 2015-10-29 at 3 24 59 am

After:
screenshot 2015-10-29 at 3 22 34 am

**Comment by alexanderzobnin** [comment]
@christianchristensen Thanks for work! I will try to test your fix soon.

**Comment by alexanderzobnin** [comment]
@christianchristensen Your code works fine with macro but causes a problems with some other metrics. I will try to find a reason of this bug. Try to test with metrics which uses regex filters.

**Comment by fabpioli** [comment]
Good afternoon, Brother ... How can we carry out the implementation in our Gragana the server? I have Grafana 3.1.1 to 3.0.4 zabbix - not have a step by step? I await your reply!

Fábio

**Comment by alexanderzobnin** [comment]
@fabpioli This PR is out of date. But I need to add this feature into the next release.

**Comment by fabpioli** [comment]
Thanks Alex! This topic has been solved with this statement! But it would be very good a new update!

**Pull request closed without merging**
