### PR TITLE
Annotation update for 2.5.1 and annotation option to show the Zabbix hostname

### PR DESCRIPTION
**Pull request by volter**
The annotation option code is a bit crude.

### CODE REVIEW

**Comment by volter** [comment]
The hostname patch could also be modified to show multiple hostnames, like it is useful for events spanning multiple hosts. This is implemented in the Zabbix frontend in some places in 2.4.

**Comment by alexanderzobnin** [comment]
@volter Thanks! I need to do some tests for your PR.

**Comment by volter** [comment]
Grafana 2.6 is out and I suppose it needs the first of my 3 commits.

**Comment by alexanderzobnin** [comment]
Yes. Sorry, but I still have no time to test it.

**Comment by alexanderzobnin** [comment]
@volter I merged your PR to develop branch for testing and fix some errors. Thanks, now it works!

**Pull request merged**
