### PR TITLE
Rewritten ptototype.query method

### PR DESCRIPTION
**Pull request by nucleusv**
This method now uses the same request doZabbixAPIRequest without code
dublication. Please check on your installation cause I have only one
metric per graph

I thinl idea is clear to remove code dublication with auth, and do all requests thru doZabbixAPIRequest

### CODE REVIEW

**Comment by nucleusv** [comment]
Alex, is it possible in grafana by default replace word alias with the metric name from zabbix api, and add check box "autoupdate metric name fro api" if it is set to true, than every time when graph is loaded to take metric name from api, not from alias field? It more convenient for zabbix users.

**Comment by alexanderzobnin** [comment]
It's good idea. I'll try to realize this feature later.

**Comment by nucleusv** [comment]
Have you fully tested this patch ?
Is it work for you from every beginning? Cause I see in console there errors sometimes.
There is cosole.log().

**Comment by alexanderzobnin** [comment]
Yes, I check for errors and for my installation all right. if you see errors again, please open issue with detailed error description.

**Pull request merged**
