### PR TITLE
Created limit and order

### PR DESCRIPTION
**Pull request by brunohl91**
Hello!

I created the option to LIMIT the number of itens to get from history and the ORDER via Zabbix API. 

I did because I was having trouble dealing with Singlestat (dashboard was heavy, taking too long to load  and consuming bandwith.)

Thanks for this excelent plugin and sorry if I did anything wrong

### CODE REVIEW

**Comment by brunohl91** [comment]
Hey @alexanderzobnin , I found out there is a little bug happening after I made this change.
When I use same data on a singlestat and on a chart, the requests seem to be cached and sometimes the chart is generated with only one point (which was the singlestat request). I am working to see why this is happening.

**Comment by alexanderzobnin** [comment]
Can you rebase this PR? I see too many temporary files as well (from jest-transform, seems).

**Comment by brunohl91** [comment]
Hey, I'm kinda new to pull to others, but is there a guide somewhere?
I corrected the bug, as it was happening on "**zabbixCachingProxy.service.js**". If you can help me I can try to pull again.

**Comment by alexanderzobnin** [comment]
@brunohl91 read the quick [PR guide](https://github.com/alexanderzobnin/grafana-zabbix/blob/master/.github/pull_request_template.md) for this repo:

**Pull request closed without merging**
